[package]
name = "ddust1n/goodsignal"
description = "Fork of Goodsignal - A fast Signal class implementation that has full feature parity with Roblox' RBXScriptSignal"
version = "0.3.2"
license = "MIT"
authors = ["Mark Langen <stravant@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# None :)
